Unsapa\IPWBundle\Entity\Promo:
    type: entity
    table: ipw_promo
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: '32'
            nullable: false
            unique: true
    lifecycleCallbacks: {  }
