Unsapa\IPWBundle\Entity\Record:
    type: entity 
    repositoryClass: Unsapa\IPWBundle\Repository\RecordRepository
    table: ipw_record
    id:
      student:
        associationKey: true
      exam:
        associationKey: true
    fields:
        document:
            type: string
            length: 255
            nullable: true
        mark:
            type: float
            length: null 
            nullable: true

    lifecycleCallbacks:
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]

    manyToOne:
      student:
        targetEntity: Unsapa\IPWBundle\Entity\User
      exam:
        targetEntity: Unsapa\IPWBundle\Entity\Exam
        inversedBy: records
        joinColumn:
          name: exam_id
          referencedColumnName: exam_id
