Unsapa\IPWBundle\Entity\Record:
    type: entity
    table: ipw_record
    id:
      student:
        associationKey: true
      exam:
        associationKey: true
    fields:
        mark:
            type: integer
            length: null
        document:
            type: string
            length: 256
            nullable: true

    lifecycleCallbacks: {  }

    manyToOne:
      student:
        targetEntity: Unsapa\IPWBundle\Entity\User
      exam:
        targetEntity: Unsapa\IPWBundle\Entity\Exam
