homepage:
    pattern: /
    defaults: { _controller: UnsapaIPWBundle:Application:index }
    
admin:
    pattern: /admin
    defaults: { _controller: UnsapaIPWBundle:Admin:index }
    
users:
    pattern: /users
    defaults: { _controller: UnsapaIPWBundle:Users:index } 
    
users_show:
    pattern: /users/{id}
    defaults: { _controller: UnsapaIPWBundle:Profile:showId }
    
users_edit:
    pattern: /users/{id}/edit
    defaults: { _controller: UnsapaIPWBundle:Profile:editId }

exams:
    pattern: /exams
    defaults: { _controller: UnsapaIPWBundle:Exams:index }

exam_add:
    pattern: /exams/add
    defaults: { _controller: UnsapaIPWBundle:Exams:add }
    
exam_add_students:
    pattern: /exams/add/students	  	
    defaults: { _controller: UnsapaIPWBundle:Promos:listStudents }

promos:
    pattern: /promos
    defaults: { _controller: UnsapaIPWBundle:Promos:index }
    
promos_add:
    pattern: /promos/add
    defaults: { _controller: UnsapaIPWBundle:Promos:add }
    
promos_edit:
    pattern: /promos/{id}/edit
    defaults: { _controller: UnsapaIPWBundle:Promos:edit }
    
exam_submit:
    pattern: /exams/submit
    defaults: { _controller: UnsapaIPWBundle:Exams:submit }

exam_show:
    pattern: /exams/{id}
    defaults: { _controller: UnsapaIPWBundle:Exams:show }

exam_students:
    pattern: /exams/{id}/students
    defaults: { _controller: UnsapaIPWBundle:Attend:examChoice }

exam_mark:
    pattern: /exams/{id}/marks
    defaults: { _controller: UnsapaIPWBundle:Attend:mark }

record_fromexam:
    pattern: /record/{examid}
    defaults: { _controller: UnsapaIPWBundle:Record:fromExam }

download_record:
    pattern: /download/{userid}/{examid}
    defaults: { _controller: UnsapaIPWBundle:Attend:download }
    
stats:
    pattern: /stats
    defaults: { _controller: UnsapaIPWBundle:Promos:stats }
  
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
