Unsapa\IPWBundle\Entity\User:
    properties:
        promo:
            - NotNull: ~
        firstname:
            - MinLength: 
                limit: 3
            - MaxLength: 
                limit: 64
        lastname: 
            - MinLength: 
                limit: 3
            - MaxLength: 
                limit: 64
        phone:
            - MinLength:
                limit: 10 
            - MaxLength:
                limit: 14
        

Unsapa\IPWBundle\Entity\Exam:
    properties:
        title:
            - NotNull: ~
            - MinLength:
                limit: 3
        promo:
            - NotNull: ~
        resp:
            - NotNull: ~
        coef:
            - NotNull: ~
            - Type: 
                type: float
        exam_date:
            - DateTime: ~
            - Unsapa\IPWBundle\Validator\Constraints\MinDate: 
                limit: "now"

Unsapa\IPWBundle\Entity\Record:
    properties:
        student:
            - NotNull: ~
        mark:
            - Min:
                limit: 0
            - Max:
                limit: 20
            - Type:
                type: float
        exam: 
            - NotNull: ~
        file:
            - File:
                maxSize: 10M
                mimeTypes: [application/pdf, application/x-pdf, application/msword, application/zip]
                mimeTypesMessage: Types de fichier valide : PDF - DOC - DOCX - ZIP
